/****************************************************************************
 * Ether Code base, version 1.0                                             *
 *==========================================================================*
 * Copyright (C) 2011 by Ron Kinney                                         *
 * All rights reserved.                                                     *
 *                                                                          *
 * This program is free software; you can redistribute it and/or modify     *
 * it under the terms of the GNU General Public License as published        *
 * by the Free Software Foundation; either version 2 of the License, or     *
 * (at your option) any later version.                                      *
 *                                                                          *
 * This program is distributed in the hope that it will be useful,          *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of           *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *
 * GNU General Public License for more details.                             *
 *                                                                          *
 * Redistribution and use in source and binary forms, with or without       *
 * modification, are permitted provided that the following conditions are   *
 * met:                                                                     *
 *                                                                          *
 * * Redistributions of source code must retain this copyright notice,      *
 *   this list of conditions and the following disclaimer.                  *
 * * Redistributions in binary form must reproduce this copyright notice    *
 *   this list of conditions and the following disclaimer in the            *
 *   documentation and/or other materials provided with the distribution.   *
 *                                                                          *
 *==========================================================================*
 * Ron Kinney (ronkinney@gmail.com)                                         *
 * Ether Homepage:   http://tdod.org/ether                                  *
 ****************************************************************************/

package org.tdod.ether.util;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public enum TaMessageManager {

   RNGGNG("RNGGNG"),
   TRS001("TRS001"),
   TRS002("TRS002"),
   TRS003("TRS003"),
   TRS004("TRS004"),
   NOTING("NOTING"),
   BYSELF("BYSELF"),
   ONEOTH("ONEOTH"),
   SEVOTH("SEVOTH"),
   TWOOTH("TWOOTH"),
   ONFLOR("ONFLOR"),
   TOODRK("TOODRK"),
   CNTSEE("CNTSEE"),
   SOMTNG("SOMTNG"),
   XARENT("XARENT"),
   NOEXIT("NOEXIT"),
   YOUGOT("YOUGOT"),
   HITRET("HITRET"),
   INVALID("INVALID"),
   GNDLEV("GNDLEV"),
   NOTRDY("NOTRDY"),
   GOTTRN("GOTTRN"),
   YOUSUI("YOUSUI"),
   YOUDED("YOUDED"),
   YOUDED1("YOUDED1"),
   YOUDED2("YOUDED2"),
   YOUDED3("YOUDED3"),
   YOUDED4("YOUDED4"),
   OTHDED("OTHDED"),
   LEVGAM("LEVGAM"),
   BYSELF2("BYSELF2"),
   MSGSNT("MSGSNT"),
   INVDSP("INVDSP"),
   INVFUL("INVFUL"),
   TOOHVY("TOOHVY"),
   LOKOTH("LOKOTH"),
   INSPCT("INSPCT"),
   INSOTH1("INSOTH1"),
   NOLSLF("NOLSLF"),
   INSOTH2("INSOTH2"),
   ARNNHR("ARNNHR"),
   POISON("POISON"),
   PARLYZ("PARLYZ"),
   DRAIN("DRAIN"),
   YOUTHR("YOUTHR"),
   YOUHNG("YOUHNG"),
   OTHPSN("OTHPSN"),
   INMOTH("INMOTH"),
   TAKINV("TAKINV"),
   ARNAWH("ARNAWH"),
   CNTGVG("CNTGVG"),
   DNTHVG("DNTHVG"),
   OTHHNG("OTHHNG"),
   OTHTHR("OTHTHR"),
   EXT12("EXT12"),
   OOP1("OOP1"),
   EXT11("EXT11"),
   ENT11("ENT11"),
   RGFALD("RGFALD"),
   CNTSIT("CNTSIT"),
   NOSITH("NOSITH"),
   NOSITM("NOSITM"),
   YOUTRP("YOUTRP"),
   OTHTRP("OTHTRP"),
   TOOFST("TOOFST"),
   HOTENV("HOTENV"),
   NOTLIT("NOTLIT"),
   BRNOUT("BRNOUT"),
   OTHOUT("OTHOUT"),
   ALRLIT("ALRLIT"),
   YOULIT("YOULIT"),
   OTHLIT("OTHLIT"),
   NOGSLF("NOGSLF"),
   TMCHGP("TMCHGP"),
   CNTGGP("CNTGGP"),
   YOUGVG("YOUGVG"),
   YOUGTG("YOUGTG"),
   JSTGVG("JSTGVG"),
   CNTGVI("CNTGVI"),
   CNTGIV("CNTGIV"),
   TRDGIV("TRDGIV"),
   DNTGIV("DNTGIV"),
   CNTHDL("CNTHDL"),
   UCNHDL("UCNHDL"),
   YOUGAV("YOUGAV"),
   YOUGET("YOUGET"),
   JSTGAV("JSTGAV"),
   NODHER("NODHER"),
   DRPITM("DRPITM"),
   NDPITM("NDPITM"),
   DRPOTH("DRPOTH"),
   DRPOTH2("DRPOTH2"),
   DNTHAV("DNTHAV"),
   DRPITM2("DRPITM2"),
   NSIHER("NSIHER"),
   YOUTAK("YOUTAK"),
   GETOTH("GETOTH"),
   GETOTH2("GETOTH2"),
   NOEQTH("NOEQTH"),
   ALRHWP("ALRHWP"),
   ALRHAR("ALRHAR"),
   YOUEQU("YOUEQU"),
   OTHEQU("OTHEQU"),
   YOUUEQ("YOUUEQ"),
   OTHUEQ("OTHUEQ"),
   NOTEQU("NOTEQU"),
   NOTWEP("NOTWEP"),
   NOTARM("NOTARM"),
   YOUDRK("YOUDRK"),
   NODRNK("NODRNK"),
   EMPTYC("EMPTYC"),
   OTHDRK("OTHDRK"),
   YOUDPT("YOUDPT"),
   YOUATE("YOUATE"),
   NOTEAT("NOTEAT"),
   OTHATE("OTHATE"),
   CTHTHT("CTHTHT"),
   CTHYET("CTHYET"),
   NOTHHR("NOTHHR"),
   ARNNCE("ARNNCE"),
   THTMOT("THTMOT"),
   THROTH12("THROTH12"),
   THRYOU1("THRYOU1"),
   TFMYOU1("TFMYOU1"),
   TFMMOT("TFMMOT"),
   TFMOTH1("TFMOTH1"),
   TFMOTH2("TFMOTH2"),
   TFMMOT2("TFMMOT2"),
   TDGYOU1("TDGYOU1"),
   TDGMOT("TDGMOT"),
   TDGOTH1("TDGOTH1"),
   TGNYOU1("TGNYOU1"),
   TGNMOT("TGNMOT"),
   TGNOTH1("TGNOTH1"),
   THROTH2("THROTH2"),
   THRMOT2("THRMOT2"),
   ATTFUM("ATTFUM"),
   FMMOTH("FMMOTH"),
   FUMYOU("FUMYOU"),
   FUMOTH("FUMOTH"),
   ATTHIT("ATTHIT"),
   ATTHTM("ATTHTM"),
   ATTDOG("ATTDOG"),
   MATDOG("MATDOG"),
   ATTGLN("ATTGLN"),
   GLNOTH("GLNOTH"),
   GLNYOU("GLNYOU"),
   ATTGNM("ATTGNM"),
   HITOTH("HITOTH"),
   MATYOU("MATYOU"),
   HITYOU("HITYOU"),
   HTMOTH("HTMOTH"),
   ATTHIT2("ATTHIT2"),
   ATTHTM2("ATTHTM2"),
   DOGOTH("DOGOTH"),
   DOGYOU("DOGYOU"),
   DGMOTH("DGMOTH"),
   GNMOTH("GNMOTH"),
   FFMYOU1("FFMYOU1"),
   FIRYOU1("FIRYOU1"),
   FDGOTH1("FDGOTH1"),
   FDGYOU1("FDGYOU1"),
   FDGMOT("FDGMOT"),
   NOFRHR("NOFRHR"),
   CFRYET("CFRYET"),
   CFRTHT("CFRTHT"),
   NOTPRJ("NOTPRJ"),
   FIROTH12("FIROTH12"),
   BNKBAL("BNKBAL"),
   BNKDEP("BNKDEP"),
   BNKWIT("BNKWIT"),
   BNKNHA("BNKNHA"),
   BNKNAC("BNKNAC"),
   BNKNCA("BNKNCA"),
   BNKANH("BNKANH"),
   BNKTMC("BNKTMC"),
   CMSG1("CMSG1"),
   CMSG2("CMSG2"),
   CMSG3("CMSG3"),
   CMSG4("CMSG4"),
   PMSG1("PMSG1"),
   PMSG2("PMSG2"),
   PMSG3("PMSG3"),
   HMSG5("HMSG5"),
   HMSG4("HMSG4"),
   HMSG3("HMSG3"),
   HMSG2("HMSG2"),
   HMSG1("HMSG1"),
   MMSG5("MMSG5"),
   MMSG4("MMSG4"),
   MMSG3("MMSG3"),
   MMSG2("MMSG2"),
   MMSG1("MMSG1"),
   KMSG1("KMSG1"),
   KMSG2("KMSG2"),
   AMSG1("AMSG1"),
   AMSG2("AMSG2"),
   IMSG1("IMSG1"),
   IMSG2("IMSG2"),
   INSP3("INSP3"),
   BMSG1("BMSG1"),
   YOUGTH("YOUGTH"),
   OTHGTH("OTHGTH"),
   NOCURE("NOCURE"),
   YOUGTC("YOUGTC"),
   OTHGTC("OTHGTC"),
   NOREMO("NOREMO"),
   YOUGTP("YOUGTP"),
   OTHGTP("OTHGTP"),
   NOREST("NOREST"),
   YOUGTR("YOUGTR"),
   OTHGTR("OTHGTR"),
   DPLGDS("DPLGDS"),
   YOUDON("YOUDON"),
   JSTDON("JSTDON"),
   PLSGDS("PLSGDS"),
   TOOINX("TOOINX"),
   BMRSPC("BMRSPC"),
   NSOHER("NSOHER"),
   BUYOTH("BUYOTH"),
   CNTAFD("CNTAFD"),
   SGNOTH("SGNOTH"),
   SLDITM("SLDITM"),
   SLDOTH("SLDOTH"),
   NOSHER("NOSHER"),
   NTTWEP("NTTWEP"),
   NTTARM("NTTARM"),
   NTTITM("NTTITM"),
   YOUGTD("YOUGTD"),
   YOUGTM("YOUGTM"),
   OTHGTD("OTHGTD"),
   OTHGTM("OTHGTM"),
   SLTLOW("SLTLOW"),
   OTHSLT("OTHSLT"),
   ROLDIC("ROLDIC"),
   GAMLOS("GAMLOS"),
   GAMWIN("GAMWIN"),
   JACKPOT("JACKPOT"),
   SLTOUT("SLTOUT"),
   DICOUT("DICOUT"),
   DICLOW("DICLOW"),
   OTHDIC("OTHDIC"),
   SLTPUL("SLTPUL"),
   CNTHNT("CNTHNT"),
   NOHNTH("NOHNTH"),
   HNTING("HNTING"),
   DNTFND("DNTFND"),
   FNDRAT("FNDRAT"),
   CNTTRK("CNTTRK"),
   NOTRKH("NOTRKH"),
   NOTRAL("NOTRAL"),
   TRKING("TRKING"),
   FOLISH("FOLISH"),
   HEWENT("HEWENT"),
   NTRSLF("NTRSLF"),
   CNTMSM("CNTMSM"),
   NOMSMH("NOMSMH"),
   MSMING("MSMING"),
   DNTMSM("DNTMSM"),
   MSMMON("MSMMON"),
   CNTTAM("CNTTAM"),
   NOTAMH("NOTAMH"),
   ALRTAM("ALRTAM"),
   TAMING("TAMING"),
   DNTTAM("DNTTAM"),
   TAMMON("TAMMON"),
   NORUNE("NORUNE"),
   RATRAT("RATRAT"),
   SHPSTL("SHPSTL"),
   YOUVOY("YOUVOY"),
   OTHVOY("OTHVOY"),
   OTHARR("OTHARR"),
   CNTVOY("CNTVOY"),
   NOTUSE("NOTUSE"),
   INDTRG("INDTRG"),
   NOUSLF("NOUSLF"),
   NRNHER("NRNHER"),
   YOURN1("YOURN1"),
   OTHRN1("OTHRN1"),
   YOURN2("YOURN2"),
   OTHRN2("OTHRN2"),
   NOSUPP("NOSUPP"),
   USMDM1("USMDM1"),
   USEDM1("USEDM1"),
   USEOT1("USEOT1"),
   USMOT1("USMOT1"),
   USMDM2("USMDM2"),
   USEDM2("USEDM2"),
   USMOT2("USMOT2"),
   USEOT2("USEOT2"),
   USEYU2("USEYU2"),
   USEYU1("USEYU1"),
   NODSLF("NODSLF"),
   YOUDRG("YOUDRG"),
   DRGYOU("DRGYOU"),
   OTHDRO("OTHDRO"),
   OTHDRI("OTHDRI"),
   CNTDRG("CNTDRG"),
   NOMCMD("NOMCMD"),
   NCFOLL("NCFOLL"),
   NCTRAL("NCTRAL"),
   NCFSLF("NCFSLF"),
   OTHCMD("OTHCMD"),
   CMDFOL("CMDFOL"),
   CMFOLL("CMFOLL"),
   CMFYOU("CMFYOU"),
   NCTSLF("NCTSLF"),
   CMDTRK("CMDTRK"),
   CTRING("CTRING"),
   CMDSTP("CMDSTP"),
   CDTNOW("CDTNOW"),
   SPLPRO("SPLPRO"),
   PROYOU("PROYOU"),
   PROOTH("PROOTH"),
   SPLCUR("SPLCUR"),
   SPLHEL("SPLHEL"),
   HELYOU("HELYOU"),
   HELOTH("HELOTH"),
   SPLINV("SPLINV"),
   SPLRGN("SPLRGN"),
   SPLRES("SPLRES"),
   SPLMCR("SPLMCR"),
   SPLMHO("SPLMHO"),
   SPLMHL("SPLMHL"),
   SPLDAM("SPLDAM"),
   SPLDAM2("SPLDAM2"),
   SPMDAM("SPMDAM"),
   SPLMDM("SPLMDM"),
   SPLMMN("SPLMMN"),
   SPLMAD("SPLMAD"),
   SPLMOT("SPLMOT"),
   SPLMMO("SPLMMO"),
   SPLYOU2("SPLYOU2"),
   SUMOTH("SUMOTH"),
   SPLSUM("SPLSUM"),
   SPLHLM("SPLHLM"),
   SPLCHM("SPLCHM"),
   CHMOTH("CHMOTH"),
   MONSUM("MONSUM"),
   SFAILD("SFAILD"),
   SSUCCF("SSUCCF"),
   SPMNEF("SPMNEF"),
   SPLNEF("SPLNEF"),
   SNMOTH("SNMOTH"),
   NEFOTH("NEFOTH"),
   NEFYOU("NEFYOU"),
   PRO1("PRO1"),
   STA1("STA1"),
   PAR1("PAR1"),
   NOSPEL("NOSPEL"),
   SPLEXH("SPLEXH"),
   ALRHVS("ALRHVS"),
   BOKFUL("BOKFUL"),
   SSNOTH("SSNOTH"),
   SPELLS("SPELLS"),
   LOOKSP("LOOKSP"),
   WARNBK("WARNBK"),
   PRGSPL("PRGSPL"),
   PRGOTH("PRGOTH"),
   LOWSPL("LOWSPL"),
   SNDTRG("SNDTRG"),
   SPLFLD("SPLFLD"),
   SFDYOU("SFDYOU"),
   NOTHER("NOTHER"),
   NSSHER("NSSHER"),
   SDNTRG("SDNTRG"),
   NOCHCH("NOCHCH"),
   NCSHER("NCSHER"),

   DICE00("DICE00"),
   DICE01("DICE01"),
   DICE02("DICE02"),
   DICE03("DICE03"),
   DICE04("DICE04"),
   DICE05("DICE05"),
   DICE06("DICE06"),
   DICE07("DICE07"),
   DICE08("DICE08"),
   DICE09("DICE09"),
   DICE10("DICE10"),

   NOJSLF("NOJSLF"),
   NOGRLD2("NOGRLD2"),
   ASKGRP("ASKGRP"),
   ASKGRP2("ASKGRP2"),
   OTHAGR1("OTHAGR1"),
   NOGRLD("NOGRLD"),
   NASGRP("NASGRP"),
   NASGRP2("NASGRP2"),
   OTHAGR2("OTHAGR2"),
   NAGSLF("NAGSLF"),
   JOIGRP("JOIGRP"),
   ACCGRP("ACCGRP"),
   OTHACG("OTHACG"),
   GRPHDR("GRPHDR"),
   NOTGRP("NOTGRP"),
   DISGRP("DISGRP"),
   GRPDIS("GRPDIS"),
   YOULDR("YOULDR"),
   GRPFOL("GRPFOL"),
   GRPHLT("GRPHLT"),
   LEVGRP("LEVGRP"),
   OTHLVG("OTHLVG"),
   LEVGRP3("LEVGRP3"),
   OTHSWG("OTHSWG"),
   YOUFOL("YOUFOL"),
   GRPARV("GRPARV"),
   JSTSHN("JSTSHN"),
   JSTSHG("JSTSHG"),
   YOUSHG("YOUSHG"),
   ALRGRP("ALRGRP"),
   OTHSHR("OTHSHR"),
   NOAPSL("NOAPSL"),
   WRNGRP("WRNGRP"),
   APTLDR("APTLDR"),
   APTYOU("APTYOU"),
   OTHAPT("OTHAPT"),
   GRPSNT("GRPSNT"),
   GTALKU("GTALKU"),
   NRGSLF("NRGSLF"),
   REMGRP("REMGRP"),
   OTHRMG("OTHRMG"),
   TOOSLW("TOOSLW"),
   WARNSP("WARNSP"),
   OUTRLM("OUTRLM"),

   NOSSPL("NOSSPL"),
   TOOBIG("TOOBIG"),
   CNTAFS("CNTAFS"),
   BYSOTH("BYSOTH"),
   NEDRST("NEDRST"),
   NOTRPR("NOTRPR"),
   GNDPRM("GNDPRM"),
   GOTPRM("GOTPRM"),

   CAMBAK("CAMBAK"),

   NOTMLE("NOTMLE"),
   GOTITM("GOTITM"),
   NGTITM("NGTITM"),
   MDGYOU("MDGYOU"),
   MDGOTH("MDGOTH"),
   MGNYOU("MGNYOU"),
   MGNOTH("MGNOTH"),
   MATOTH("MATOTH"),
   MFMYOU("MFMYOU"),
   MFMOTH("MFMOTH"),
   CNTMOV("CNTMOV"),
   LEVCBT("LEVCBT"),
   ATTEXH("ATTEXH"),
   MONDEF("MONDEF"),
   GOTTRS("GOTTRS"),
   GTLTRS("GTLTRS"),
   NOFTHR("NOFTHR"),
   NOASLF("NOASLF"),
   MONENT("MONENT"),

   OOP2("OOP2"),
   EXT13("EXT13"),
   ENT13("ENT13"),

   TRS011("TRS011"),
   TRS012("TRS012"),

   RACE("RACE"),
   COMPLX("COMPLX"),
   EYECOL("EYECOL"),
   HARCOL("HARCOL"),
   HARSTL("HARSTL"),
   HARLNG("HARLNG"),
   CLASS("CLASS"),

   STATS("STATS"),
   STATS2("STATS2"),
   STATS3("STATS3"),

   ACTMSG2("ACTMSG2"),
   THRITIS("THRITIS"),
   YOURUB2("YOURUB2"),
   OTHRUB("OTHRUB"),
   
   LAST_ITEM("");


   private static Log _log = LogFactory.getLog(TaMessageManager.class);

   private final String      _key;
   private static Properties _props = initialize();

   /**
    * Creates a new MessageManager.
    * @param key the message key.
    */
   TaMessageManager(String key) {
      _key = key;
   }

   /**
    * Gets the message.
    * @return the message.
    */
   public String getMessage() {
      String message = _props.getProperty(_key);
      if (message == null) {
         _log.error("key " + _key + " was null!");
      }
      return  message;
   }

   /**
    * Initializes all messages by reading the data from a file.
    * @return the Properties object.
    */
   private static Properties initialize() {
      Properties props = new Properties();
      FileInputStream fileInputStream = null;
      try {
         String fileName = PropertiesManager.getInstance().getProperty(PropertiesManager.TA_MESSAGE_DATA_FILE);
         _log.info("Loading message file " + fileName);
         fileInputStream = new FileInputStream(fileName);
         props.load(fileInputStream);
      } catch (Exception e) {
         _log.fatal(e, e);
         System.exit(1);
      } finally {
         if (fileInputStream != null) {
            try {
               fileInputStream.close();
            } catch (IOException e) {
               _log.fatal(e, e);
               System.exit(1);
            }
         }
      }
      return props;
   }

}
